# Generated by Django 4.0.6 on 2022-07-08 15:21

from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_place_opening'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='header',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kopfzeile'),
        ),
        migrations.AlterField(
            model_name='info',
            name='days',
            field=utils.fields.SelectArrayField(base_field=models.CharField(blank=True, choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag'), (5, 'Samstag'), (6, 'Sonntag')], max_length=15, null=True), blank=True, null=True, size=None, verbose_name='Anzeigetage'),
        ),
    ]
