# Generated by Django 4.0.6 on 2022-07-08 15:56

from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_info_header_alter_info_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='days',
            field=utils.fields.SelectArrayField(base_field=models.IntegerField(blank=True, choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag'), (5, 'Samstag'), (6, 'Sonntag')], null=True), blank=True, null=True, size=None, verbose_name='Anzeigetage'),
        ),
    ]
