# Generated by Django 4.0.6 on 2022-07-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_owlimages_news_is_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='whoweare',
            field=models.TextField(blank=True, verbose_name='Über uns'),
        ),
        migrations.AlterField(
            model_name='owlimage',
            name='img',
            field=models.ImageField(unique=True, upload_to='owl-images', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=127, verbose_name='Name'),
        ),
    ]
