# Generated by Django 4.0.6 on 2022-07-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_place_whoweare_alter_owlimage_img_alter_place_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='whoweare',
            new_name='about',
        ),
    ]
