# Generated by Django 4.0.6 on 2022-07-10 11:20

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_rename_whoweare_place_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kopfzeile')),
                ('title', models.CharField(max_length=255, verbose_name='Schlagzeile')),
                ('description_list', django_jsonform.models.fields.ArrayField(base_field=models.TextField(max_length=1023, verbose_name='Text'), help_text='Jede Spalte der Liste wird in einen neuen Absatz im Intro geschreiben.', size=10, verbose_name='Texte')),
                ('url_path', models.CharField(max_length=32, verbose_name='URL Pfad')),
            ],
            options={
                'verbose_name': 'Into Text',
                'verbose_name_plural': 'Intro Texte',
            },
        ),
    ]
