# Generated by Django 4.0.6 on 2022-07-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_category_slug'),
        ('content', '0009_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='meals',
            field=models.ManyToManyField(blank=True, related_name='place', to='food.meal'),
        ),
    ]
