# Generated by Django 4.0.6 on 2022-07-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_place_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=142),
        ),
    ]
