# Generated by Django 4.0.6 on 2022-07-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Emailadresse')),
                ('first_name', models.CharField(blank=True,
                 max_length=127, null=True, verbose_name='Vorname')),
                ('last_name', models.CharField(blank=True, max_length=127, null=True, verbose_name='Nachname')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Geburtstag')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ist aktiv')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Ist Admin')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Benutzer:in',
                'verbose_name_plural': 'Benutzer:innen'},
        ),
    ]
