# Generated by Django 4.0.6 on 2022-07-10 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_place_meals'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('first_name', models.CharField(max_length=127, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=127, verbose_name='Nachname')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('message', models.TextField(max_length=2055, verbose_name='Nachricht')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.place', verbose_name='Ort')),
            ],
            options={
                'verbose_name': 'Kontaktformular',
                'verbose_name_plural': 'Kontaktformulare',
            },
        ),
    ]
