# Generated by Django 4.0.6 on 2022-07-08 16:03

from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='saisonal_month',
            field=utils.fields.SelectArrayField(base_field=models.CharField(blank=True, choices=[('1', 'Januar'), ('2', 'Februar'), ('3', 'März'), ('4', 'April'), ('5', 'Mai'), ('6', 'Juni'), ('7', 'Juli'), ('8', 'August'), ('9', 'September'), ('10', 'Oktober'), ('11', 'November'), ('12', 'Dezember')], max_length=2, null=True), blank=True, null=True, size=None, verbose_name='Saisonale Monate'),
        ),
    ]
