# Generated by Django 4.0.6 on 2022-07-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_meal_saisonal_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Ist vorhanden:'),
        ),
    ]
