# Generated by Django 4.0.6 on 2022-07-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_meal_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=511, null=True, verbose_name='Beschreibung'),
        ),
    ]
