# Generated by Django 4.0.6 on 2022-07-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='img',
            field=models.ImageField(default='meal-images/berries.jpg',
                                    upload_to='meal-images', verbose_name='Bild'),
        ),
    ]
